#!/usr/bin/with-contenv bash

# make folder
mkdir -p /config/comskip

[[ ! -e /config/comskip/comskip.ini ]] && \
    cp /defaults/comskip.ini.bak /config/comskip/comskip.ini
[[ ! -e /config/comskip/flagcommercials.sh ]] && \
    cp /defaults/flagcommercials.sh.bak /config/comskip/flagcommercials.sh

# Make the script executable
chmod +x /config/comskip/flagcommercials.sh
# add the script to the path
ln -sf /config/comskip/flagcommercials.sh /usr/local/bin/flagcommercials
 
#Don't need to worry about overall permissions - they are taken care of later with the plex scripts
